# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Global configurations
## Default
# source: ./
destination: ./public
# collections_dir: ./
# plugins_dir: _plugins # takes an array of strings and loads plugins in that order
# layouts_dir: _layouts
# data_dir: _data
# includes_dir: _includes
# sass:
#   sass_dir: _sass
# collections:
#   posts:
#     output: true
## Handling Reading
# safe: false
# include: [".htaccess"]
# exclude:
# keep_files: [".git", ".svn"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
# strict_front_matter : false
## Filtering Content
# show_drafts : null
# limit_posts : 0
# future : false
# unpublished : false
## Plugins
# whitelist : []
# plugins : []
## Conversion
markdown : kramdown
# lsi : false
# excerpt_separator : "\n\n"
# incremental : false
## Serving
# detach : false
# port : 4000
# host : 127.0.0.1
# baseurl: "" # the subpath of your site, e.g. /blog, does not include hostname.
# show_dir_listing    : false
# Outputting
# permalink: pretty
permalink: /:categories/:title/
paginate_path: /page:num
timezone: Asia/Jakarta

# quiet : false
# verbose : false
defaults: # Front matter defaults
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
    - scope:
          path: ""
      values:
          layout: "default"

# liquid:
#   error_mode : warn
#   strict_filters : false
#   strict_variables : false
## Markdown Processors
kramdown:
    auto_ids : true
    entity_output : as_char
    toc_levels : [1, 2, 3, 4, 5, 6]
    smart_quotes : lsquo,rsquo,ldquo,rdquo
    input : GFM
    syntax_highlighter: rouge
    hard_wrap : false
    footnote_nr : 1
    show_warnings : false

# Site
title: kiraio
description: >- # this means to ignore newlines until "baseurl:"
    Unleash Your Creativity.
logo: ""
url: "https://kiraio-moe.github.io" # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%b %-d, %Y"
show_excerpts: false # set to true to show excerpts on the homepage
# page_excerpts: false
under_maintenance: false
version: 2.0.0
#====================

# Analytics
google_analytics:

#====================

# SNS
author:
    name: "Bayu Satiyo"
    email: itsyuukunz@gmail.com
    deviantart: kiraio
    facebook: kiraio.moe
    github: kiraio-moe
    instagram: kiraio.moe
    pixiv: kiraio
    twitter: kiraio_moe
    youtube: "@kiraio"

#====================

# Build settings
# theme: minima
plugins:
    #  - "github-pages"
    # - "jekyll-feed"
    # - "jekyll-gist"
    # - "jekyll-last-modified-at"
    #  - "jekyll-multiple-languages-plugin"
    # - "jekyll-paginate-v2"
    #  - "jekyll-polyglot" bug at Win platform
    - "jekyll-redirect-from"
    - "jekyll-sass-converter"
    - "jekyll-seo-tag"
    - "jekyll-sitemap"

#====================

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - scripts/
    - logs/
    - ./*.md

#====================

# Pagination plugin
# jekyll-paginate-v2 settings
# permalink: /:year/:month/
# pagination:
#   enabled: true
#   per_page: 12
#   sort_reverse: true
#   sort_field: 'date'
#   title: ':title'
#   trail:
#     before: 2
#     after: 2

#====================

# jekyll-sass-converter settings
# https://github.com/jekyll/jekyll-sass-converter
sass:
    style: "compressed"
    # sass_dir:
    # load_paths:
    # sourcemap: "always"
    # quiet_deps: false
    # verbose: false
#====================

# Multi-languages plugin
# jekyll-multiple-languages-plugin
# https://github.com/kurtsson/jekyll-multiple-languages-plugin/
# languages: ["id", "en"]
# default_locale_in_subfolder: true
# exclude_from_localizations: ["assets", "bin", "logs", "public", "_scss"] # In code, these specific files should be referenced via baseurl_root. E.g. <link rel="stylesheet" href="{{ "/css/bootstrap.css" | prepend: site.baseurl_root }}"/>
lang: "id"
dir: "left"
